
name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ver estructura del proyecto
        run: |
          echo "Contenido del repositorio:"
          ls -la
          echo "Contenido de proj:"
          ls -la proj

      - name: Dar permisos a Gradle
        working-directory: ./proj
        run: chmod +x ./gradlew

      - name: Compilar APK Debug
        working-directory: ./proj
        run: ./gradlew assembleDebug --no-daemon

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: DACATECH-APK
          path: proj/app/build/outputs/apk/debug/app-debug.apk
